CREATE DATABASE PR_OVA;

USE PR_OVA;

CREATE TABLE IF NOT EXISTS TIPO_USUARIO(
	ID 				INT UNSIGNED AUTO_INCREMENT,
	DESCRIPCION 	VARCHAR(50) NOT NULL,
	CONSTRAINT   	PK_ID_TIPO_USUARIO PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
	ID 				INT UNSIGNED AUTO_INCREMENT,
	NOMBRES 		VARCHAR(100) NOT NULL,
	APELLIDOS 		VARCHAR(100) NOT NULL,
	EMAIL 			VARCHAR(100) NOT NULL UNIQUE,
	PASS 			VARCHAR(50) NOT NULL,
	AVATAR			LONGBLOB,
	ID_TIPO_USUARIO INT UNSIGNED NOT NULL,
	CONSTRAINT   PK_ID_USUARIO PRIMARY KEY(ID),
	CONSTRAINT   FK_TIPO_USUARIO_USUARIO FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID)
);


CREATE TABLE IF NOT EXISTS PROBLEMA(
	ID 			INT UNSIGNED AUTO_INCREMENT,
    PIN 		INT UNSIGNED UNIQUE NOT NULL,
    TITULO 		VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    IMAGEN 		LONGBLOB,
    PREGUNTA	TEXT,
    FECHA		DATE,
    OBSERVACIONES TEXT,
    ID_USUARIO	INT UNSIGNED NOT NULL,
    CONSTRAINT PK_ID_PROBLEMA PRIMARY KEY(ID),
    CONSTRAINT FK_USUARIO_PROBLEMA 	FOREIGN KEY(ID_USUARIO) 	REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS RESPUESTA(
	ID 				INT UNSIGNED AUTO_INCREMENT,
	DESCRIPCION 	VARCHAR(150) NOT NULL,
    CORRECTA 		BOOLEAN NOT NULL,
    ID_PROBLEMA		INT UNSIGNED NOT NULL,
    CONSTRAINT 		PK_ID_RESPUESTA PRIMARY KEY(ID),
    CONSTRAINT 		FK_RESPUESTA_PROBLEMA FOREIGN KEY(ID_PROBLEMA) REFERENCES PROBLEMA(ID)
);

CREATE TABLE IF NOT EXISTS SUGERENCIA(
	ID 				INT UNSIGNED AUTO_INCREMENT,
	DESCRIPCION 	VARCHAR(200) NOT NULL,
    ID_PROBLEMA		INT UNSIGNED NOT NULL,
    CONSTRAINT 		PK_ID_SUGERENCIA PRIMARY KEY(ID),
	CONSTRAINT 		FK_SUGERENCIA_PROBLEMA FOREIGN KEY(ID_PROBLEMA) REFERENCES PROBLEMA(ID)
);

CREATE TABLE IF NOT EXISTS RTA_PROBLEMA(
	ID_USUARIO	INT UNSIGNED NOT NULL,
    ID_PROBLEMA	INT UNSIGNED NOT NULL,
    RESPUESTA	VARCHAR(150) NOT NULL,
    CANTIDAD_SUGERENCIAS INT(2) UNSIGNED NOT NULL,
    ANEXO_POLYA	LONGBLOB,
    CONSTRAINT PK_RTA_USUARIO_PROBLEMA PRIMARY KEY(ID_USUARIO, ID_PROBLEMA),
    CONSTRAINT FK_RTA_USUARIO 	FOREIGN KEY(ID_USUARIO) 	REFERENCES USUARIO(ID),
    CONSTRAINT FK_RTA_PROBLEMA 	FOREIGN KEY(ID_PROBLEMA) 	REFERENCES PROBLEMA(ID)
);
